language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '12'
script:
  - npm run test

jobs:
  include:
    - stage: Production
      before_script:
        - npm run build:docs
      node_js: '12'
      name: deploy_docs
      if: branch = master AND env(TRAVIS_PULL_REQUEST) IS false
      script: npm run deploy-docs
    - name: npm_release
      node_js: '12'
      before_script:
        - npm run build
      if: (branch = master OR branch = next) AND env(TRAVIS_PULL_REQUEST) IS false
      script: npm run semantic-release
    - name: produce_coverage
      node_js: '12'
      before_script:
        - npm run test:cov
      if: branch = master AND env(TRAVIS_PULL_REQUEST) IS false
      script: npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
